"""
Django settings for freebsdashboard project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4f56p%+542c0s=$cfem51pyg$g(k)u-3@qw(h+_ff^+w)7q#6i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Application definition

INSTALLED_APPS = [
	'ZFSAdmin.apps.ZFSAdminConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django_tables2',
	'django_q',
]

MIDDLEWARE_CLASSES = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'freebsdashboard.my_middleware.TimezoneMiddleware',
]

# django-q

Q_CLUSTER = {
	'name': 'freebsdashboard',
	'workers': 1,  # 8
	'recycle': 1,  # 500
	'timeout': 1000000,
	'compress': True,
	'cpu_affinity': 1,
	'sync': False,  # False
	'save_limit': 250,
	'queue_limit': 500,
	'label': 'Django Q',
	'redis': {
		'host': '127.0.0.1',
		'port': 6379,
		'db': 0,
		'password': None,
		'socket_timeout': None,
		'charset': 'utf-8',
		'errors': 'strict',
		'unix_socket_path': None,
	}
}

ROOT_URLCONF = 'freebsdashboard.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'django.core.context_processors.request',
				'freebsdashboard.custom_context_processors.default_strings',
			],
		},
	},
]

WSGI_APPLICATION = 'freebsdashboard.wsgi.application'

# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'db_freebsdashboard',
		'USER': 'freebsdashboard',
		'PASSWORD': 'tester_password_2016',
		'HOST': 'localhost',
		'PORT': '',
	}
}

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGIN_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-gb'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_ROOT = '/usr/local/freebsdashboard/web/static/'
MEDIA_ROOT = '/usr/local/freebsdashboard/web/media/'

# LOGGING
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
		},
		'simple': {
			'format': '%(asctime)s %(levelname)s %(message)s'
		}
	},
	'handlers': {
		'console': {
			'level': 'DEBUG',
			'class': 'logging.StreamHandler',
			'formatter': 'simple'
		},
		'file': {
			'level': 'DEBUG',
			'class': 'logging.FileHandler',
			'filename': '/var/log/django_main/debug.log',
			'formatter': 'verbose'
		},
	},
	'loggers': {
		'main': {
			'handlers': ['console', 'file'],
			'level': 'WARNING',
			'propagate': True,
		},
		'django': {
			'handlers': ['file'],
			'level': 'DEBUG',
			'propagate': True,
		},
	},
}

'''PROJECT SETTINGS '''

PROJECT_ROOT = '/usr/local/freebsdashboard/'

DEFAULT_SITE_NAME = 'FreeBSDashboard'

# for REAL data, use system_calls.sh, for dummy data (demo) use demo/system_calls_demo.sh
SYSTEM_CALL_SCRIPT_NAME = '/demo/system_calls_demo.sh'

DEFAULT_FOOTER_TEXT = 'Do not eat the blueberry crumble!'
