# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('process_id', models.CharField(max_length=255, null=True)),
                ('error_flag', models.BooleanField(default=False)),
                ('error_detail', models.CharField(max_length=255, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZfsDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZfsSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(blank=True, null=True)),
                ('retention', models.BigIntegerField(default=10080)),
                ('name', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zfssnapshot',
            unique_together=set([('datetime_created', 'dataset')]),
        ),
    ]
